from __future__ import annotations

from pathlib import Path

import pandas as pd
from jinja2 import Environment, StrictUndefined

from judgebench.benchmark.statistics import describe_distribution, summarize_scores

_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{{ title }}</title>
  <style>
    body { font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Arial; margin: 2rem; }
    .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 1rem; }
    .card { border: 1px solid #e5e7eb; border-radius: 12px; padding: 1rem; }
    table { width: 100%; border-collapse: collapse; margin-top: 1rem; }
    th, td { border-bottom: 1px solid #e5e7eb; padding: 0.5rem; text-align: left; vertical-align: top; }
    code { background: #f3f4f6; padding: 0.1rem 0.25rem; border-radius: 6px; }
  </style>
</head>
<body>
  <h1>{{ title }}</h1>
  <p><strong>Local-first report</strong> generated by <code>judgebench</code>.</p>

  <h2>Summary</h2>
  <div class="grid">
    <div class="card"><div>Mean final score</div><h3>{{ summary.mean_final_score | round(2) }}</h3></div>
    <div class="card"><div>Mean semantic similarity</div><h3>{{ summary.mean_semantic_similarity | round(2) }}</h3></div>
    <div class="card"><div>Mean correctness</div><h3>{{ summary.mean_correctness | round(2) }}</h3></div>
    <div class="card"><div>Mean completeness</div><h3>{{ summary.mean_completeness | round(2) }}</h3></div>
    <div class="card"><div>Mean hallucination risk (higher=worse)</div><h3>{{ summary.mean_hallucination_risk | round(2) }}</h3></div>
    <div class="card"><div>Mean clarity</div><h3>{{ summary.mean_clarity | round(2) }}</h3></div>
  </div>

  <h2>Final score distribution</h2>
  <div class="card">
    <div>min={{ distro.min | round(1) }}, p25={{ distro.p25 | round(1) }}, median={{ distro.median | round(1) }}, p75={{ distro.p75 | round(1) }}, max={{ distro.max | round(1) }}, mean={{ distro.mean | round(1) }}</div>
  </div>

  <h2>Examples (first 50)</h2>
  <table>
    <thead>
      <tr>
        {% for col in columns %}<th>{{ col }}</th>{% endfor %}
      </tr>
    </thead>
    <tbody>
      {% for row in rows %}
      <tr>
        {% for col in columns %}<td>{{ row[col] }}</td>{% endfor %}
      </tr>
      {% endfor %}
    </tbody>
  </table>
</body>
</html>
"""


def write_html_report(df: pd.DataFrame, path: str | Path, *, title: str = "JudgeBench Report") -> None:
    env = Environment(undefined=StrictUndefined, autoescape=True)
    template = env.from_string(_TEMPLATE)
    summary = summarize_scores(df)
    distro = describe_distribution(df, "final_score")
    view = df.head(50).copy()
    columns = [c for c in ["id", "final_score", "semantic_similarity", "correctness", "completeness", "hallucination_risk", "clarity", "reasoning"] if c in view.columns]
    html = template.render(
        title=title,
        summary=summary.model_dump(),
        distro=distro,
        columns=columns,
        rows=view[columns].astype(str).to_dict(orient="records"),
    )
    out_path = Path(path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(html, encoding="utf-8")

